### ISSUE TITLE
Feature Request: Add "Area Name" as a variable.

### ISSUE THREAD

**Issue by alexander-cato** [pschmitt/hass-rename-entities#1]
It would be great to be able to use the device's area name as a variable. 
My ideal naming convention would be:

The friendly name: "RoomName DeviceName" (Room name needed in friendly name due to the way Siri works when passing devices to homekit)
The entity name would ideally be "type.integration_roomname_devicename"

**Comment by pschmitt** [comment]
The device area is available as `AREA_ID`.

For the entity area: will do :)

**Comment by pschmitt** [comment]
Changes i introduced:

- `DEVICE_AREA_ID` contains the area of the *device*
- `AREA_ID` is the area id of the *entity* (that defaults to `DEVICE_AREA_ID` when it is not set explicitly)

**Comment by alexander-cato** [comment]
Amazing, thank you so much!
